In [2]:
import pandas as pd
import numpy as np

In [6]:
pd.read_csv('players.csv')

,player_id,name,position,age,team,games_played,minutes,points,assists,personal_fouls,technical_fouls
0,1,Adeyemi,PG,24,Lagos Leopards,28,896,336,196,58,0
1,2,Okafor,SG,29,Lagos Leopards,30,960,540,120,64,1
2,3,Balogun,SF,26,Lagos Leopards,27,864,410,140,70,0
3,4,Diallo,PF,31,Lagos Leopards,29,928,380,60,112,2
4,5,Nwosu,C,28,Lagos Leopards,30,900,340,40,128,1
5,6,Owusu,PG,22,Accra Aces,25,700,245,175,45,0
6,7,Appiah,SG,27,Accra Aces,28,868,460,90,58,0
7,8,Danquah,SF,25,Accra Aces,26,780,360,110,66,0
8,9,Bello,PF,30,Accra Aces,29,870,330,55,118,3
9,10,Chukwu,C,33,Accra Aces,27,756,260,35,130,1
10,11,Eneh,PG,23,Kano Kings,24,672,230,168,42,0
11,12,Gyamfi,SG,26,Kano Kings,29,870,470,95,60,0
12,13,Hassan,SF,28,Kano Kings,30,930,420,120,74,1
13,14,Ikpeba,PF,24,Kano Kings,22,660,255,48,95,2
14,15,Jalloh,C,31,Kano Kings,28,812,290,30,120,2
15,16,Kamara,PG,20,Abuja Pythons,18,486,160,120,30,0
16,17,Lawal,SG,25,Abuja Pythons,27,810,430,80,52,0
17,18,Mohammed,SF,29,Abuja Pythons,29,870,395,105,68,0
18,19,Nkrumah,PF,27,Abuja Pythons,26,780,300,50,105,1
19,20,Oduya,C,32,Abuja Pythons,30,870,315,32,132,1
20,21,Peprah,PG,26,Kumasi Giants,19,342,120,90,22,0
21,22,Quansah,SG,21,Kumasi Giants,15,240,120,30,16,0
22,23,Rahman,SF,33,Kumasi Giants,11,154,60,18,14,0
23,24,Sowah,PF,28,Kumasi Giants,22,374,150,25,55,0
24,25,Tetteh,C,30,Kumasi Giants,24,384,140,15,60,1

Perform Exploritory Data Analysis

In [7]:
df.shape

(25, 11)

In [10]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   player_id        25 non-null     int64
 1   name             25 non-null     str
 2   position         25 non-null     str
 3   age              25 non-null     int64
 4   team             25 non-null     str
 5   games_played     25 non-null     int64
 6   minutes          25 non-null     int64
 7   points           25 non-null     int64
 8   assists          25 non-null     int64
 9   personal_fouls   25 non-null     int64
 10  technical_fouls  25 non-null     int64
dtypes: int64(8), str(3)
memory usage: 2.3 KB

In [9]:
df.describe()

,player_id,age,games_played,minutes,points,assists,personal_fouls,technical_fouls
count,25.000000,25.000000,25.000000,25.000000,25.000000,25.00000,25.000000,25.000000
mean,13.000000,27.120000,25.320000,711.040000,300.640000,81.88000,71.760000,0.640000
std,7.359801,3.609247,5.014313,237.288938,125.877877,52.22493,36.298852,0.860233
min,1.000000,20.000000,11.000000,154.000000,60.000000,15.00000,14.000000,0.000000
25%,7.000000,25.000000,24.000000,660.000000,230.000000,35.00000,52.000000,0.000000
50%,13.000000,27.000000,27.000000,810.000000,315.000000,80.00000,64.000000,0.000000
75%,19.000000,30.000000,29.000000,870.000000,395.000000,120.00000,105.000000,1.000000
max,25.000000,33.000000,30.000000,960.000000,540.000000,196.00000,132.000000,3.000000

In [11]:
 df.head(5)

,player_id,name,position,age,team,games_played,minutes,points,assists,personal_fouls,technical_fouls
0,1,Adeyemi,PG,24,Lagos Leopards,28,896,336,196,58,0
1,2,Okafor,SG,29,Lagos Leopards,30,960,540,120,64,1
2,3,Balogun,SF,26,Lagos Leopards,27,864,410,140,70,0
3,4,Diallo,PF,31,Lagos Leopards,29,928,380,60,112,2
4,5,Nwosu,C,28,Lagos Leopards,30,900,340,40,128,1

In [13]:
df.tail(5)

,player_id,name,position,age,team,games_played,minutes,points,assists,personal_fouls,technical_fouls
20,21,Peprah,PG,26,Kumasi Giants,19,342,120,90,22,0
21,22,Quansah,SG,21,Kumasi Giants,15,240,120,30,16,0
22,23,Rahman,SF,33,Kumasi Giants,11,154,60,18,14,0
23,24,Sowah,PF,28,Kumasi Giants,22,374,150,25,55,0
24,25,Tetteh,C,30,Kumasi Giants,24,384,140,15,60,1

In [14]:
print (df.columns.tolist())

['player_id', 'name', 'position', 'age', 'team', 'games_played', 'minutes', 'points', 'assists', 'personal_fouls', 'technical_fouls']

In [25]:
print (df.iloc[2])
print (df.iloc[0,5])

player_id                       3
name                      Balogun
position                       SF
age                            26
team               Lagos Leopards
games_played                   27
minutes                       864
points                        410
assists                       140
personal_fouls                 70
technical_fouls                 0
Name: 2, dtype: object
28

In [28]:
print(df[df['name'] == 'Diallo'])

   player_id    name position  age            team  games_played  minutes  \
3          4  Diallo       PF   31  Lagos Leopards            29      928

   points  assists  personal_fouls  technical_fouls
3     380       60             112                2

In [29]:
print (df.loc[df['team'] == 'Lagos leopards'])

Empty DataFrame
Columns: [player_id, name, position, age, team, games_played, minutes, points, assists, personal_fouls, technical_fouls]
Index: []

In [34]:
guards = df[df['position'].isin(['PG','SG'])]
print(guards.shape)
print(guards.head(5))

(10, 11)
    player_id     name position  age            team  games_played  minutes  \
0           1  Adeyemi       PG   24  Lagos Leopards            28      896
1           2   Okafor       SG   29  Lagos Leopards            30      960
5           6    Owusu       PG   22      Accra Aces            25      700
6           7   Appiah       SG   27      Accra Aces            28      868
10         11     Eneh       PG   23      Kano Kings            24      672

    points  assists  personal_fouls  technical_fouls
0      336      196              58                0
1      540      120              64                1
5      245      175              45                0
6      460       90              58                0
10     230      168              42                0

In [35]:
print (df[(df['points'] > 20) & (df['assists'] > 20)])

    player_id      name position  age            team  games_played  minutes  \
0           1   Adeyemi       PG   24  Lagos Leopards            28      896
1           2    Okafor       SG   29  Lagos Leopards            30      960
2           3   Balogun       SF   26  Lagos Leopards            27      864
3           4    Diallo       PF   31  Lagos Leopards            29      928
4           5     Nwosu        C   28  Lagos Leopards            30      900
5           6     Owusu       PG   22      Accra Aces            25      700
6           7    Appiah       SG   27      Accra Aces            28      868
7           8   Danquah       SF   25      Accra Aces            26      780
8           9     Bello       PF   30      Accra Aces            29      870
9          10    Chukwu        C   33      Accra Aces            27      756
10         11      Eneh       PG   23      Kano Kings            24      672
11         12    Gyamfi       SG   26      Kano Kings            29      870
12         13    Hassan       SF   28      Kano Kings            30      930
13         14    Ikpeba       PF   24      Kano Kings            22      660
14         15    Jalloh        C   31      Kano Kings            28      812
15         16    Kamara       PG   20   Abuja Pythons            18      486
16         17     Lawal       SG   25   Abuja Pythons            27      810
17         18  Mohammed       SF   29   Abuja Pythons            29      870
18         19   Nkrumah       PF   27   Abuja Pythons            26      780
19         20     Oduya        C   32   Abuja Pythons            30      870
20         21    Peprah       PG   26   Kumasi Giants            19      342
21         22   Quansah       SG   21   Kumasi Giants            15      240
23         24     Sowah       PF   28   Kumasi Giants            22      374

    points  assists  personal_fouls  technical_fouls
0      336      196              58                0
1      540      120              64                1
2      410      140              70                0
3      380       60             112                2
4      340       40             128                1
5      245      175              45                0
6      460       90              58                0
7      360      110              66                0
8      330       55             118                3
9      260       35             130                1
10     230      168              42                0
11     470       95              60                0
12     420      120              74                1
13     255       48              95                2
14     290       30             120                2
15     160      120              30                0
16     430       80              52                0
17     395      105              68                0
18     300       50             105                1
19     315       32             132                1
20     120       90              22                0
21     120       30              16                0
23     150       25              55                0

In [13]:
pos_map = {
    'PG': 'Point Guard',
    'SG': 'Shooting Guard',
    'SF': 'Small Forward',
    'PF': 'Power Forward',
    'C': 'Center'
}

# Replace 'position' with your actual column name
df['position_name'] = df['position'].map(pos_map).fillna('Unknown')
print(df[['position', 'position_name']].head(10))

  position   position_name
0       PG     Point Guard
1       SG  Shooting Guard
2       SF   Small Forward
3       PF   Power Forward
4        C          Center
5       PG     Point Guard
6       SG  Shooting Guard
7       SF   Small Forward
8       PF   Power Forward
9        C          Center

In [4]:
import pandas as pd
df = pd.read_csv('players.csv')
df.isna().sum()

player_id          0
name               0
position           0
age                0
team               0
games_played       0
minutes            0
points             0
assists            0
personal_fouls     0
technical_fouls    0
dtype: int64

In [3]:
import os
import pandas as pd

# 1. Create the 'data' directory if it doesn't exist
os.makedirs('data', exist_ok=True)

# 2. Load the DataFrame
df = pd.read_csv('players.csv')

# 3. Save to the target path
df.to_csv("data/players_practice.csv", index=False)
print("Saved.")

Saved.

In [5]:
import os
print("Files in main directory:", os.listdir("."))
if os.path.exists("data"):
    print("Files in 'data' directory:", os.listdir("data"))

Files in main directory: ['.DS_Store', 'players.csv', 'pip install pandas numpy.py', 'Basketball.ipynb', 'data']
Files in 'data' directory: ['players_practice.csv']

In [6]:
import pandas as pd
import numpy as np

pd.set_option("display.max_columns", 50)

# Load available dataset
players = pd.read_csv("players.csv")

print("players:", players.shape)

# Uncomment these once matches.csv and teams.csv are added to the directory:
# matches = pd.read_csv("matches.csv")
# teams = pd.read_csv("teams.csv")
# print("matches:", matches.shape)
# print("teams:", teams.shape)

players: (25, 11)

In [2]:
import pandas as pd

# Load players dataset
players = pd.read_csv("players.csv")

print("shape:", players.shape)
players.head()

shape: (25, 11)

,player_id,name,position,age,team,games_played,minutes,points,assists,personal_fouls,technical_fouls
0,1,Adeyemi,PG,24,Lagos Leopards,28,896,336,196,58,0
1,2,Okafor,SG,29,Lagos Leopards,30,960,540,120,64,1
2,3,Balogun,SF,26,Lagos Leopards,27,864,410,140,70,0
3,4,Diallo,PF,31,Lagos Leopards,29,928,380,60,112,2
4,5,Nwosu,C,28,Lagos Leopards,30,900,340,40,128,1

In [1]:
gitinit

NameError: name 'gitinit' is not defined

In [3]:
gitinit

NameError: name 'gitinit' is not defined

In [4]:
pip install git

ERROR: Could not find a version that satisfies the requirement git (from versions: none)
ERROR: No matching distribution found for git
Note: you may need to restart the kernel to use updated packages.

In [5]:
pip install python-git

Collecting python-git
  Downloading python_git-2018.2.1-py3-none-any.whl.metadata (5.8 kB)
Collecting send2trash (from python-git)
  Downloading send2trash-2.1.0-py3-none-any.whl.metadata (4.1 kB)
Downloading python_git-2018.2.1-py3-none-any.whl (10 kB)
Downloading send2trash-2.1.0-py3-none-any.whl (17 kB)
Installing collected packages: send2trash, python-git
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2/2 [python-git]
Successfully installed python-git-2018.2.1 send2trash-2.1.0
Note: you may need to restart the kernel to use updated packages.

In [ ]:
git init

SyntaxError: invalid syntax (2830201818.py, line 1)

In [7]:
%pip install GitPython

Collecting GitPython
  Downloading gitpython-3.2.1-py3-none-any.whl.metadata (13 kB)
Collecting gitdb<5,>=4.0.1 (from GitPython)
  Downloading gitdb-4.0.12-py3-none-any.whl.metadata (1.2 kB)
Collecting smmap<6,>=3.0.1 (from gitdb<5,>=4.0.1->GitPython)
  Downloading smmap-5.0.3-py3-none-any.whl.metadata (4.6 kB)
Downloading gitpython-3.2.1-py3-none-any.whl (231 kB)
Downloading gitdb-4.0.12-py3-none-any.whl (62 kB)
Downloading smmap-5.0.3-py3-none-any.whl (24 kB)
Installing collected packages: smmap, gitdb, GitPython
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3/3 [GitPython]
Successfully installed GitPython-3.2.1 gitdb-4.0.12 smmap-5.0.3
Note: you may need to restart the kernel to use updated packages.

In [8]:
git init

SyntaxError: invalid syntax (2830201818.py, line 1)

In [11]:
!git init
!git add .
!git commit -m "Initial commit"
!git branch -M main

Reinitialized existing Git repository in /Users/cyrilmthembu/Documents/Pandas/.git/
[main (root-commit) 835f020] Initial commit
 6 files changed, 1593 insertions(+)
 create mode 100644 .DS_Store
 create mode 100644 Basketball.ipynb
 create mode 100644 data/players_practice.csv
 create mode 100644 epl_2023_24_SOURCE.md
 create mode 100644 pip install pandas numpy.py
 create mode 100644 players.csv

In [17]:
!git remote set-url origin https://github.com/comfitnessconsultants-pixel/Basketball.git
!git push -u origin main

Username for 'https://github.com':

OSError: [Errno 5] Input/output error

In [19]:
!git status -sb
!git branch --show-current
!git rev-parse HEAD
!git ls-remote origin "refs/heads/$(git branch --show-current)"

## main
 M Basketball.ipynb
main
835f02023082b178f7432a8f20b45ee37421c651

In [20]:
!git rev-parse HEAD
!git ls-remote --heads origin main

835f02023082b178f7432a8f20b45ee37421c651

In [21]:
!git branch --show-current
!git ls-remote --heads origin main

main

In [22]:
!git ls-remote --heads origin main

In [23]:
!git remote -v

origin	https://github.com/comfitnessconsultants-pixel/Basketball.git (fetch)
origin	https://github.com/comfitnessconsultants-pixel/Basketball.git (push)

In [24]:
!git push --progress -u origin main

Username for 'https://github.com':

OSError: [Errno 5] Input/output error

In [25]:
!git status -sb

## main
 M Basketball.ipynb

In [26]:
!git remote -v

origin	https://github.com/comfitnessconsultants-pixel/Basketball.git (fetch)
origin	https://github.com/comfitnessconsultants-pixel/Basketball.git (push)

In [27]:
!git add Basketball.ipynb
!git commit -m "Update basketball notebook"

[main e56feda] Update basketball notebook
 1 file changed, 398 insertions(+)

In [28]:
!git push -u origin main

Username for 'https://github.com':

OSError: [Errno 5] Input/output error

In [29]:
!git ls-remote --heads origin

In [30]:
!git ls-remote --heads origin; echo "Exit code: $?"

Exit code: 0

In [31]:
!GIT_TERMINAL_PROMPT=0 git push --progress -u origin main

fatal: could not read Username for 'https://github.com': terminal prompts disabled